server:
  port: ${app.port:8080}
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

springdoc:
  api-docs:
    path: /api-docs

mybatis-plus:
  configuration:
    default-enum-type-handler: com.nexxus.common.BaseEnumTypeHandler
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml